[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/namsral/flag"
  version = "1.7.4-pre"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.8.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/segmentio/kafka-go"